dbt-cloud:
    project-id: 70471823542460

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'autosense_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'autosense_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  autosense_dbt:
    # Bronze Layer - Parsed raw data as views
    stage:
      +materialized: table
      +schema: stg
      +tags: ['bronze', 'raw', 'staged']

    # Silver Layer - Cleaned and transformed data as tables
    curated:
      +materialized: table
      +schema: curated
      +tags: ['silver', 'cleaned', 'transformed']

    # Gold Layer - Star schema dimensional models for analytics
    semantic:
      +materialized: table
      +schema: semantic
      +tags: ['gold', 'semantic', 'analytics']

vars:
  # Switzerland geographic bounding box for location validation
  switzerland_lat_min: 45.817995
  switzerland_lat_max: 47.808455
  switzerland_lon_min: 5.955911
  switzerland_lon_max: 10.492294

seeds:
  autosense_dbt:
    city_name_mapping:
      +column_types:
        city_name_raw: varchar(100)
        city_name_standardized: varchar(100)
      +tags: ['reference', 'mapping']
